Error Time: 2025-03-20 13:42:20
Error Message: module 'datetime' has no attribute 'now'

Traceback (most recent call last):
  File "/home/ym/code/ML_training/week3/schwefel/train_gbdt.py", line 1312, in <module>
    mse, r2, pearson = main()
  File "/home/ym/code/ML_training/week3/schwefel/train_gbdt.py", line 908, in main
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
AttributeError: module 'datetime' has no attribute 'now'
